/**
 * Metric Templates
 * 
 * Preset configurations for common program types.
 * These templates populate program_metric_definitions when
 * creating a new program via the metric builder UI.
 * 
 * is_primary = true  → Basis Health Score calculation & primary progress bar
 * is_primary = false → Secondary/informational metric, shown as chips
 */

import { Database } from '@/types/database'

type MetricDefinitionInsert = Omit<
  Database['public']['Tables']['program_metric_definitions']['Insert'],
  'id' | 'program_id' | 'created_at'
>

export interface MetricTemplate {
  key: string
  label: string
  description: string
  metrics: MetricDefinitionInsert[]
}

export const METRIC_TEMPLATES: MetricTemplate[] = [
  {
    key: 'advertising',
    label: 'Paid Traffic & Advertising',
    description: 'Template lengkap untuk program iklan berbayar (Meta, Google, TikTok). Pelacakan funnel lengkap dari impressions hingga ROAS dan Area Scores.',
    metrics: [
      // ─── RAW INPUT: BUDGET & SPEND ───────────────────────────────
      {
        metric_key: 'budget_plan',
        label: 'Budget Plan',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'ad_spend',
        unit_label: 'Rp',
        display_order: 1,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'ad_spend',
        label: 'Ad Spend',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'ad_spend',
        unit_label: 'Rp',
        display_order: 2,
        formula: null,
        target_direction: 'lower_is_better',
      },

      // ─── RAW INPUT: REACH & IMPRESSIONS ──────────────────────────
      {
        metric_key: 'reach',
        label: 'Reach',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'leads', // ikut agregasi leads group
        unit_label: 'orang',
        display_order: 3,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'impressions',
        label: 'Impressions',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'tayangan',
        display_order: 4,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: CLICKS ────────────────────────────────────────
      {
        metric_key: 'link_clicks',
        label: 'Link Clicks',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'klik',
        display_order: 5,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: LANDING PAGE ──────────────────────────────────
      {
        metric_key: 'lp_views',
        label: 'Landing Page Views',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'view',
        display_order: 6,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: LEADS ─────────────────────────────────────────
      {
        metric_key: 'leads',
        label: 'Leads',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: true,
        is_target_metric: true,
        metric_group: 'leads',
        unit_label: 'lead',
        display_order: 7,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'qualified_leads',
        label: 'Qualified Leads',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'leads',
        unit_label: 'lead',
        display_order: 8,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'invalid_leads',
        label: 'Invalid / Fake Leads',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'lead',
        display_order: 9,
        formula: null,
        target_direction: 'lower_is_better',
      },

      // ─── RAW INPUT: CONVERSION PATH ───────────────────────────────
      {
        metric_key: 'wa_conversations',
        label: 'WA Conversations',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'chat',
        display_order: 10,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'form_started',
        label: 'Form Started',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'orang',
        display_order: 11,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'form_submitted',
        label: 'Form Submitted',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'orang',
        display_order: 12,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'initiated_registration',
        label: 'Initiated Registration',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'orang',
        display_order: 13,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: REVENUE & ACQUISITION ──────────────────────────
      {
        metric_key: 'revenue',
        label: 'Revenue from Paid Traffic',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: true,
        is_target_metric: true,
        metric_group: 'revenue',
        unit_label: 'Rp',
        display_order: 14,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'user_count',
        label: 'Closing (User Baru)',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: true,
        is_target_metric: true,
        metric_group: 'user_acquisition',
        unit_label: 'user',
        display_order: 15,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: CREATIVE ──────────────────────────────────────
      {
        metric_key: 'creative_tested',
        label: 'Creative Tested',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'creative',
        display_order: 15,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'creative_winners',
        label: 'Creative Winners',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'creative',
        display_order: 16,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: CHANNEL (opsional, multi-channel) ─────────────
      {
        metric_key: 'channel_leads',
        label: 'Channel Leads',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'lead',
        display_order: 17,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'total_leads_all_channels',
        label: 'Total Leads (All Channels)',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'lead',
        display_order: 18,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'channel_qualified_leads',
        label: 'Channel Qualified Leads',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'lead',
        display_order: 19,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'total_ql_all_channels',
        label: 'Total Qualified Leads (All Channels)',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'lead',
        display_order: 20,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── RAW INPUT: BASELINE & TARGET ──
      {
        metric_key: 'baseline_cpc',
        label: 'Baseline CPC',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 21,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'baseline_cpm',
        label: 'Baseline CPM',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 22,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'baseline_cost_lp_view',
        label: 'Baseline Cost per LP View',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 23,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'target_cpl',
        label: 'Target CPL',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 24,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'target_cpql',
        label: 'Target CPQL',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 25,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'target_wa_chat_rate',
        label: 'Target WA Chat Rate',
        data_type: 'percentage',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 26,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'target_cost_reg',
        label: 'Target Cost per Reg',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 27,
        formula: null,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'target_roas',
        label: 'Target ROAS',
        data_type: 'float',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'x',
        display_order: 28,
        formula: null,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'trend_efficiency',
        label: 'Trend Efficiency',
        data_type: 'percentage',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 29,
        formula: null,
        target_direction: 'higher_is_better',
      },

      // ─── CALCULATED: AD PERFORMANCE ──────────────────────────────
      {
        metric_key: 'frequency',
        label: 'Frequency',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'impressions / reach',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'x',
        display_order: 30,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'ctr',
        label: 'CTR (Link)',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'link_clicks / impressions',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'efficiency',
        unit_label: '%',
        display_order: 31,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cpc',
        label: 'CPC',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / link_clicks',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 32,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'cpm',
        label: 'CPM',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / impressions * 1000',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 33,
        target_direction: 'lower_is_better',
      },

      // ─── CALCULATED: LANDING PAGE ────────────────────────────────
      {
        metric_key: 'lp_view_rate',
        label: 'LP View Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'lp_views / link_clicks',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'efficiency',
        unit_label: '%',
        display_order: 34,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cost_per_lp_view',
        label: 'Cost per LP View',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / lp_views',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 35,
        target_direction: 'lower_is_better',
      },

      // ─── CALCULATED: LEAD FUNNEL ──────────────────────────────────
      {
        metric_key: 'lead_conversion_rate',
        label: 'Lead Conversion Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'leads / lp_views',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'conversion',
        unit_label: '%',
        display_order: 36,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cpl',
        label: 'CPL',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / leads',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 37,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'qualified_lead_rate',
        label: 'Qualified Lead Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'qualified_leads / leads',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'conversion',
        unit_label: '%',
        display_order: 38,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cpql',
        label: 'Cost per Qualified Lead',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / qualified_leads',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 39,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'invalid_lead_rate',
        label: 'Invalid Lead Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'invalid_leads / leads',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 40,
        target_direction: 'lower_is_better',
      },

      // ─── CALCULATED: CONVERSION PATH ─────────────────────────────
      {
        metric_key: 'wa_chat_rate',
        label: 'WA Chat Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'wa_conversations / link_clicks',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'conversion',
        unit_label: '%',
        display_order: 41,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cost_per_wa_conv',
        label: 'Cost per WA Chat',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / wa_conversations',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 42,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'cpp',
        label: 'CPP (Cost per Closing)',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / user_count',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 43,
        target_direction: 'lower_is_better',
      },
      {
        metric_key: 'form_completion_rate',
        label: 'Form Completion Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'form_submitted / form_started',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'conversion',
        unit_label: '%',
        display_order: 43,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'cost_per_reg',
        label: 'Cost per Initiated Reg',
        data_type: 'currency',
        input_type: 'calculated',
        formula: 'ad_spend / initiated_registration',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'Rp',
        display_order: 44,
        target_direction: 'lower_is_better',
      },

      // ─── CALCULATED: REVENUE & EFFICIENCY ────────────────────────
      {
        metric_key: 'roas',
        label: 'ROAS',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'revenue / ad_spend',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'efficiency',
        unit_label: 'x',
        display_order: 45,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'marketing_efficiency',
        label: 'Marketing Efficiency',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'roas / target_roas',
        is_primary: false,
        is_target_metric: false,
        metric_group: 'efficiency',
        unit_label: '%',
        display_order: 46,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'budget_utilization',
        label: 'Budget Utilization',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'ad_spend / budget_plan',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 47,
        target_direction: 'lower_is_better',
      },

      // ─── CALCULATED: CREATIVE & CHANNEL ──────────────────────────
      {
        metric_key: 'creative_winner_rate',
        label: 'Creative Winner Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'creative_winners / creative_tested',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 48,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'channel_contribution_leads',
        label: 'Channel Leads Contribution',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'channel_leads / total_leads_all_channels',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 49,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'channel_contribution_ql',
        label: 'Channel QL Contribution',
        data_type: 'percentage',
        input_type: 'calculated',
        formula: 'channel_qualified_leads / total_ql_all_channels',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: '%',
        display_order: 50,
        target_direction: 'higher_is_better',
      },

      // ─── CALCULATED: SCORES (IF Logic) ─────────────────────────────
      {
        metric_key: 'score_ctr',
        label: 'Score: CTR',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(ctr > 0.02, 100, IF(ctr > 0.015, 60, 20))',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 51,
        show_on_dashboard: false,
        show_on_tv: false,
      },
      {
        metric_key: 'score_cpc',
        label: 'Score: CPC',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(cpc <= baseline_cpc, 100, IF(cpc <= baseline_cpc * 1.2, 60, 20))',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 52,
        show_on_dashboard: false,
        show_on_tv: false,
      },
      {
        metric_key: 'score_frequency',
        label: 'Score: Frequency',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(frequency >= 1.5, IF(frequency <= 3, 100, 60), 20)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 53,
        show_on_dashboard: false,
        show_on_tv: false,
      },
      {
        metric_key: 'score_lp_view_rate',
        label: 'Score: LP View Rate',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(lp_view_rate >= 0.8, 100, IF(lp_view_rate >= 0.7, 60, 20))',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 54,
        show_on_dashboard: false,
        show_on_tv: false,
      },
      {
        metric_key: 'score_roas',
        label: 'Score: ROAS',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(roas >= target_roas, 100, roas / target_roas * 100)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 55,
        show_on_dashboard: false,
        show_on_tv: false,
      },
      {
        metric_key: 'score_cpl',
        label: 'Score: CPL',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'IF(cpl <= target_cpl, 100, IF(cpl <= target_cpl * 1.2, 60, 20))',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 56,
        show_on_dashboard: false,
        show_on_tv: false,
      },

      // ─── CALCULATED: AREA SCORES (AVG) ────────────────────────────
      {
        metric_key: 'area_score_ad_appeal',
        label: 'Area Score: Iklan Menarik?',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'AVG(score_ctr, score_cpc, score_frequency)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 57,
        show_on_dashboard: true,
        show_on_tv: true,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'area_score_traffic_quality',
        label: 'Area Score: Traffic Berkualitas?',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'AVG(score_lp_view_rate)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 58,
        show_on_dashboard: true,
        show_on_tv: true,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'area_score_leads',
        label: 'Area Score: Lead Masuk?',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'AVG(score_cpl)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 59,
        show_on_dashboard: true,
        show_on_tv: true,
        target_direction: 'higher_is_better',
      },
      {
        metric_key: 'area_score_revenue',
        label: 'Area Score: Uang Iklan Sehat?',
        data_type: 'float',
        input_type: 'calculated',
        formula: 'AVG(score_roas)',
        is_primary: false,
        is_target_metric: false,
        metric_group: null,
        unit_label: 'poin',
        display_order: 60,
        show_on_dashboard: true,
        show_on_tv: true,
        target_direction: 'higher_is_better',
      },
    ],
  },
  {
    key: 'sales_basic',
    label: 'Sales Dasar (Rp + User)',
    description: 'Template standar untuk program sales yang melacak pendapatan dan jumlah peserta.',
    metrics: [
      {
        metric_key: 'revenue',
        label: 'Pendapatan',
        data_type: 'currency',
        input_type: 'manual',
        is_primary: true,         // PRIMARY: basis Health Score
        is_target_metric: true,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'Rp',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 1,
        metric_group: 'revenue',
        formula: null,
      },
      {
        metric_key: 'user_count',
        label: 'Jumlah Peserta',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: true,         // PRIMARY: basis Health Score
        is_target_metric: true,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'peserta',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 2,
        metric_group: 'user_acquisition',
        formula: null,
      },
    ],
  },
  {
    key: 'qualitative_only',
    label: 'Kualitatif (Milestone Only)',
    description: 'Program yang hanya melacak pencapaian milestone tanpa target angka.',
    metrics: [],
  },
  {
    key: 'customer_service',
    label: 'Customer Service',
    description: 'Untuk tim CS yang melacak tiket, response time, dan kepuasan pelanggan.',
    metrics: [
      {
        metric_key: 'tiket_masuk',
        label: 'Tiket Masuk',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'tiket',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 1,
        metric_group: 'leads',
        formula: null,
      },
      {
        metric_key: 'tiket_selesai',
        label: 'Tiket Diselesaikan',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: true,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'tiket',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 2,
        metric_group: 'user_acquisition',
        formula: null,
      },
      {
        metric_key: 'resolution_rate',
        label: 'Resolution Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        is_primary: false,
        is_target_metric: false,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: '%',
        show_on_dashboard: true,
        show_on_tv: false,
        display_order: 3,
        metric_group: 'conversion',
        formula: 'tiket_selesai / tiket_masuk',
      },
    ],
  },
  {
    key: 'mou_partnership',
    label: 'Kemitraan & MoU',
    description: 'Template untuk program kerja sama strategis (MoU) yang berfokus pada kuantitas tanda tangan agreement atau MoU baru.',
    metrics: [
      {
        metric_key: 'mou_signed',
        label: 'Tanda Tangan MoU',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: true,
        is_target_metric: true,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'MoU',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 1,
        metric_group: 'user_acquisition',
        formula: null,
      },
      {
        metric_key: 'agreement_leads',
        label: 'Prospek Kerja Sama',
        data_type: 'integer',
        input_type: 'manual',
        is_primary: false,
        is_target_metric: false,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: 'prospek',
        show_on_dashboard: true,
        show_on_tv: true,
        display_order: 2,
        metric_group: 'leads',
        formula: null,
      },
      {
        metric_key: 'conversion_rate',
        label: 'Lead to MoU Rate',
        data_type: 'percentage',
        input_type: 'calculated',
        is_primary: false,
        is_target_metric: false,
        monthly_target: null,
        target_direction: 'higher_is_better',
        unit_label: '%',
        show_on_dashboard: true,
        show_on_tv: false,
        display_order: 3,
        metric_group: 'conversion',
        formula: 'mou_signed / agreement_leads',
      },
    ],
  },
]

export const METRIC_TEMPLATE_MAP = Object.fromEntries(
  METRIC_TEMPLATES.map(t => [t.key, t])
)
